theme: jekyll-theme-minimal
title: Artificial Intelligence for Counter Intelligence
description: Official Project Website for the Project Artificial Intelligence for Counter Intelligence
show_downloads: false
logo: /images/help.jpg
