theme: jekyll-theme-minimal
title: PROJECT COMP-COIN
description: The Project COMP-COIN (Computational Methods for Counter Intelligence) is a multinational academic initiative aimed at studying the unique fingerprints of extremist outfits using tools from the domain of Artificial Intelligence
logo: images/29694626_1870837259653282_3503950039716170886_n.jpg
show_downloads: true
