theme: jekyll-theme-minimal
title: Artificial Intelligence for Counter Intelligence
description: Official Project Website for the Project Artificial Intelligence for Counter Intelligence. You can help us save the future by participating in this initiative. Scroll down to know more. 
show_downloads: false
logo: /images/help.jpg
